In [58]:
import numpy as np
import matplotlib.pyplot as plt
import copy

z_1 = np.array([[0.387, 0.290, 0.194, 0.129],
                [0.368, 0.288, 0.202, 0.142],
                [0.387, 0.290, 0.194, 0.129],
                [0.368, 0.288, 0.202, 0.142]])

z_2 = np.array([[0.5, 0.5, 0.0, 0.0],
                [0.435, 0.435, 0.065, 0.065],
                [0.5, 0.5, 0.0, 0.0],
                [0.435, 0.435, 0.065, 0.065]])

z_3 = np.array([[0.2, 0.4, 0.2, 0.2],
                [0.206, 0.382, 0.206, 0.206],
                [0.2, 0.4, 0.2, 0.2],
                [0.206, 0.382, 0.206, 0.206]])

print(0.206 + 0.382 + 0.206 + 0.206)

0.9999999999999999


In [ ]:
def random_walk_zad1(z_matrix: np.ndarray, epsilon: float):

    N_nodes = len(z_matrix)
    countings = np.zeros(N_nodes)
    probabs = np.ones(N_nodes)
    probabs_old = probabs
    probabs_indexes = np.arange(0, N_nodes, 1)
    current_node = 0
    probabs_diff = epsilon + 1
    iteration = 0

    while(probabs_diff > epsilon):

        iteration += 1

        probabs_old = probabs.copy()

        current_node = np.random.choice(probabs_indexes, p = z_matrix[current_node])
        countings[current_node] += 1

        probabs_diff = 0
        for node in range(N_nodes):
            probabs[node] = countings[node]/iteration
            probabs_diff += np.abs(probabs[node] - probabs_old[node])
            
    return probabs

def random_walk_zad2(z_matrix: np.ndarray, epsilon: float):

    N_nodes = len(z_matrix)
    countings = np.zeros(N_nodes)
    probabs = np.ones(N_nodes)
    probabs_old = probabs
    probabs_indexes = np.arange(0, N_nodes, 1)
    current_node = 0
    probabs_diff = epsilon + 1
    iteration = 0

    while(probabs_diff > epsilon):

        iteration += 1

        probabs_old = probabs.copy()

        U = np.random.uniform(0,1)
        if U < 0.85 and z_matrix[current_node, current_node] != 1:
            current_node = np.random.choice(probabs_indexes, p = z_matrix[current_node])
        else:
            p_else = np.ones(N_nodes)/(N_nodes - 1)
            p_else[current_node] = 0
            current_node = np.random.choice(probabs_indexes, p = p_else)

        countings[current_node] += 1

        probabs_diff = 0
        for node in range(N_nodes):
            probabs[node] = countings[node]/iteration
            probabs_diff += np.abs(probabs[node] - probabs_old[node])
            
    return probabs

def page_rank_zad3(A: np.ndarray, epsilon: float):

    A = A.T
    N_nodes = len(A)
    Nepsilon = N_nodes*epsilon
    v = np.ones(N_nodes)/N_nodes
    v_before = np.zeros(N_nodes)
    diff = Nepsilon + 1
    
    while(diff > Nepsilon):

        v_before = v.copy()
        v = A @ v

        diff = 0
        for i in range(N_nodes):
            diff += np.abs(v[i] - v_before[i])
    
    return v

def page_rank_zad4(A: np.ndarray, epsilon: float):

    N_nodes = len(A)
    Nepsilon = N_nodes*epsilon
    v = np.ones(N_nodes)/N_nodes
    v_before = np.zeros(N_nodes)
    diff = Nepsilon + 1
    B = np.ones_like(A)/N_nodes

    p = 0.15
    M = (1 - p)*A + p*B

    while(diff > Nepsilon):

        v_before = v.copy()
        v = M @ v

        diff = 0
        for i in range(N_nodes):
            diff += np.abs(v[i] - v_before[i])
    
    return v

probabs = random_walk_zad1(z_matrix = z_1, epsilon = 1e-5)
print(probabs)
probabs = random_walk_zad2(z_matrix = z_1, epsilon = 1e-5)
print(probabs)
v = page_rank_zad3(A = z_2, epsilon= 1e-5)
print(v)

v = page_rank_zad4(A = z_2.T, epsilon= 1e-5)
print(v)

[0.38151789 0.28820191 0.19726269 0.13301751]
[0.35432138 0.28154596 0.20878602 0.15534665]
[0.4675 0.4675 0.0325 0.0325]
[0.434875 0.434875 0.065125 0.065125]
